### PR TITLE
v5: update bill of materials and adjust 2x20 footprint

### PR DESCRIPTION
**Pull request by garlick**
In the process of setting up a PCBA assembly order at JLC, parts were identified by the JLC engineer that can be locally sourced through LCSC.  The biggie is the SMT 2x20 header.  The Harwin part was like $5 but the replacement is less than $1.  However, its alignment posts are slightly bigger, so the footprint required a minor adjustment to enlarge the holes by 0.2mm dia.

This updates the BOM and that footprint.

### CODE REVIEW

**Comment by quorten** [comment]
Changing J4 to SMT places its leads too close for comfort to the SN74LVC161284DLR chip.  A little bit of extra space would make it easier to do hand cleanup after reflow soldering.  Either rotating 90 degrees or moving it further away would work.

**Comment by quorten** [comment]
R4 is from Uniroyal while the other resistors are from Yageo, any specific reason for this?

**Comment by garlick** [comment]
Hey good thought on J4.  I'll see if I can fix that.

On R4, that's the part that JLC selected, so I assumed "manufacturing reasons"  :shrug: .  I'm not sure it matters.

**Review by quorten — APPROVED** [review]
Nice update, now it all looks good to me.  To double-check things overall, I took another look at all the PCB traces and verified them with the pinouts and that still looks good.

**Comment by garlick** [comment]
Thanks for the review effort!  I'll merge this now.

**Pull request merged**
