### PR TITLE
hardware_v3: add BOM manufacturer part numbers

### PR DESCRIPTION
**Pull request by quorten**
Add manufacturer part numbers for all components.  All of the selected parts are available on Digi-Key and the field "Digi-Key_PN" was also added for the Digi-Key part numbers, just like the KiCad Digi-Key parts library uses.  I opted to pick some of the better parts for the pin headers... higher temperature insulators on the pin headers, gold-plated mating contacts for the large pin headers.  Likewise, I picked Panasonic resistors since they end up being the same price as the cheapest except when bought in bulk.

Also I've added a link to the datasheet for the CAT24C32 EEPROM.

Here are the condensed results of generating the BoM:

| Reference | Quantity | Digi-Key_PN         | MPN              | Manufacturer                    |
| --------- | -------- | ------------------- | ---------------- | ------------------------------- |
| J1        | 1        | 952-2262-ND         | M20-9990246      | Harwin Inc.                     |
| J2        | 1        | S5750-20-ND         | NPPN202AFCN-RC   | Sullins Connector Solutions     |
| J3        | 1        | 23-0877602616-ND    | 0877602616        | Molex                           |
| R2        | 1        | P10.0KCCT-ND        | ERJ-6ENF1002V    | Panasonic Electronic Components |
| R3 R4     | 2        | P3.90KCCT-ND        | ERJ-6ENF3901V    | Panasonic Electronic Components |
| R5        | 1        | P1.40KCCT-ND        | ERJ-6ENF1401V    | Panasonic Electronic Components |
| U1        | 1        | CAT24C32WI-GT3CT-ND | CAT24C32WI-GT3   | ON Semiconductor                |
| U2        | 1        | 296-8467-1-ND       | SN74LVC161284DLR | Texas Instruments               |

N.B.: Digi-Key subtotal today says $6.73.

### CODE REVIEW

**Comment by garlick** [comment]
Fantastic!

Great that the changes are focused - just adding a BOM that people can use to order parts for the v3 board that's currently on OSHPARK makes sense as a first step.  Also, it's really really nice from a review point of view, and for clean history when each commit of a PR does one focused thing like this IMHO.

One question:  should the component info be in `project_components/parport.lib`?  I'm still trying to wrap my head around what a stable, standalone KiCAD project looks like in github so your thoughts would be appreciated.

Since you took the trouble to make a github markdown page for the BOM would you like to go ahead and add that to the PR as a separate commit that drops it in `hardware_v3/BOM.md` with a link from the main `README.md`?

Then this PR can close #32.

Again thanks alot!

**Comment by quorten** [comment]
Yeah, I think the component info should also go in the local library files like `project_components/parport.lib`.  Ideally, it would have been put in there in an early stage at least for chips and the like, resistors and capacitors may have the part numbers added individually.  I think I'll add that in quick.

Definitely, I'll add `hardware_v3/BOM.md` and also make note of the standoffs and screws there like v2 did.

Speaking of capacitors, the V3 design is missing one as per #28, but I'll add a note about this in the `BOM.md` while I'm at it.

**Comment by quorten** [comment]
For the sake of consistency with the v2 Bill of Materials, I've also added the Package, Description, and Notes fields.

**Comment by garlick** [comment]
This looks perfect @quorten.  Ready to merge?

**Comment by quorten** [comment]
@garlick Sure, I'm ready.  Closes issue #30... looks like you've accidentally reference the wrong number earlier.

**Comment by quorten** [comment]
Oops, not yet, I've noticed I got the table headings mixed up on the BOM part listing the mounting parts.  I'll push a quick fix.

**Comment by quorten** [comment]
There we go, now I'm ready, there was an extra table column in the last table, but only in the header.

**Comment by garlick** [comment]
Thanks again!

**Pull request merged**
