### PR TITLE
hardware_v4: add bypass capacitors, reroute traces

### PR DESCRIPTION
**Pull request by quorten**
These changes should close issues #28 and #29.

* Do not route trace under resistor R5.  Move U2 upward to facilitate rerouting this trace without adding more vias.

* Also make sure footprints between schematic and PCB are in sync.

* Update BOM with new parts.

* Hardware version needs to be bumped due to PCB changes.  Version numbers in schematic and PCB source changed, new files will need to be generated later.

Here are some graphical indicators of the changes contained in this pull request.

pullreq_drawing1

pullreq_drawing2

### CODE REVIEW

**Comment by quorten** [comment]
A few additional comments are worthwhile for discussion.  On one hand, I find it somewhat curiously interesting that the EEPROM chip worked just fine without a decoupling capacitor, but hey, being physically close to the Raspberry Pi board as a HAT is plausibly good fortune for avoiding the problems that would require the decoupling capacitors.

Technically I'm intending on using `pi-parport` with a Raspberry Pi Zero, as a first step I thought I'd try the board out as-is, but since my setup would likely involve connecting the two boards with a short cable, the missing bypass capacitors seemed too glaring of a problem.

**Comment by garlick** [comment]
Thank you @quorten - really nice job presenting the changes pictorially, and I appreciate that you fixed this design before moving on to the zero.

Would you mind tacking on a commit to rename `hardware_v3` to just plain `hardware` and fixing the links in README.md?   Probably the oshpark link in the README.md should then say "version 3 is shared..." until I get a chance to put up a v4.

When you've got a good design for the zero, perhaps that can go in `hardware_zero` or similar?

(All that's up for discussion if you have other ideas?)

**Comment by quorten** [comment]
Yeah, sure thing, I'll rename the directories and polish that up when ready.  Actually, I ended up creating a Raspberry Pi Zero board design faster than I expected, I could probably finish it up pretty soon and create a pull request for that.  And in doing so, I noticed there was another problem with traces running under resistor R3 on the v3 board, that should be an easy fix by moving R3 down and running in the space between instead.

pizero

**Comment by garlick** [comment]
Beautiful!  Love it!

**Comment by quorten** [comment]
I decided to restructure the directories so that all versions are placed in a single directory, `hardware` instead of `hardware_old`.  `hardware_latest` is setup to be a symlink to the latest hardware version.

One thing that I saw I got tripped up on in `hardware_v3` was that the schematic specified 0805 package resistors at the EEPROM, but the PCB used 0603 footprints.  I'm guessing that was a last minute decision to change those on the board to make positioning them easier when they are packed right next to each other, but I figure that bigger is probably better for hand soldering, and technically you could have squeezed 0805 packages onto the v3 board just fine.

cmp_foots

The other trace is now rerouted so that it doesn't go under resistor R3, I decided to move the vias closer to the EEPROM so now the I2C wires mostly travel across the back side of the board.  I also fixed some minor CAD issues, so now the KiCad 3D view properly shows the rounded corners of the board outline!  (Board outline just barely not closed at one spot.)

pullreq_drawing3

pr2_back

**Comment by quorten** [comment]
Looks like GitHub doesn't like following the symlink for the board image in README.md, that will have to be fixed.

**Comment by garlick** [comment]
Great improvements!

> One thing that I saw I got tripped up on in hardware_v3 was that the schematic specified 0805 package resistors at the EEPROM, but the PCB used 0603 footprints

Doh!   The 0603's came from the Kicad pi hat template, and I must not have forced the pcb to update after changing the footprint assignment in the schematic.  Good catch!

**Comment by garlick** [comment]
> Board outline just barely not closed at one spot.

Double-doh!

I'm happy to hit the merge button if you're all done making changes @quorten.  I'm super pleased with these improvements, thank you!

**Comment by quorten** [comment]
@garlick One last change, related to the footprint swap-out, the reference R3 is probably better put to the right than the bottom, that's just the default location it ended up after force-updating the footprint changes.

**Comment by quorten** [comment]
Alright, looks good now.

pi-parport

**Comment by quorten** [comment]
@garlick Ready for you to merge.

**Pull request merged**
