### PR TITLE
driver: fixes for linux kernel >= 5.10

### PR DESCRIPTION
**Pull request by garlick**
Supporth newer kernels
- update drivers/parport for linux-5.10
- drop MODULE_SUPPORTED_DEVICE call (deprecated  somewhere between 5.10 and 5.13)

### CODE REVIEW

**Review by quorten — APPROVED** [review]

**Comment by quorten** [comment]
Definitely the driver version to include is a sticky situation, I have to admit that I was staring into the diff a little bit longer than I needed to before realizing it was all copied files.

**Comment by quorten** [comment]
But the other thing about dropping MODULE_SUPPORTED_DEVICE call, is this something that "retro Raspberry Pi" enthusiasts might want to put back in?

**Comment by garlick** [comment]
> But the other thing about dropping MODULE_SUPPORTED_DEVICE call, is this something that "retro Raspberry Pi" enthusiasts might want to put back in when using older kernel versions?

I don't think so :-)  It sounds like it was never really used for anything:

https://github.com/torvalds/linux/commit/6417f03132a6952cd17ddd8eaddbac92b61b17e0

I'll fix the commit message on the parport update so it's more clear that it's copied code.  Sorry about that!

**Comment by garlick** [comment]
Force pushed with commit message changes (no code changes).  I'll go ahead and merge. Thanks for keeping an eye on things @quorten!

**Comment by garlick** [comment]
> Definitely the driver version to include is a sticky situation

Yeah it's really lame to have to do that forever.  I just closed raspberrypi/linux#3923 due to lack of response for a very long time (kind of forgot about it).  I'll resubmit with only the parport enablement and see if that goes any better.

**Pull request merged**
